config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do

  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :posts, only: [:create, :destroy]
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :user_id, presence: true
  validates :content, presence: true
  @posts = Post.paginate(:page => params[:page], :per_page => 8)
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

def feed
  Micropost.where("user_id = ?", id)
end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end

  def destroy
    current_user = User.find(params[:id])
    current_user.destroy
    flash[:success] = "User deleted."
    redirect_to admin_users_url
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  before_action :authenticate_user!

  def home
    if signed_in?
    @post  = current_user.microposts.build
    @feed_items = current_user.feed.paginate(page: params[:page])
  end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 8) 
  end

  def create
      @post = current_user.posts.build(post_params)
      if @post.save
        flash[:success] = "Post created!"
        redirect_to root_url
      else
      @feed_items = []
      render 'admin/home'
    end
    end

    def destroy
    end

    private

      def post_params
        params.require(:post).permit(:content)
      end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
     @posts = @user.posts.paginate(page: params[:page])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/home.html.haml
- if signed_in?
  .row
    %aside.span4S
      %section= render 'shared/post_form'
  .span8
  %h3 Post Feed
  = render 'shared/feed'
= image_tag(@idea.picture_url, :width=>600) if @idea.picture.present?
= cktext_area_tag(«test_area», «Ckeditor is the best»)
= cktext_area_tag(«content», «Ckeditor», :input_html => {:cols => 10, :rows => 20}, :toolbar => ‘Easy’)
- else
  .center.hero-unit
    %h1 Bless

app/views/admin/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>Admin</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Delete user', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      </tr>
    <% end %>
  </tbody>
</table>



<br>

<%= link_to 'New Post', new_admin_post_path %>

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  %li= link_to 'Edit account', edit_user_registration_path
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path
- if user_signed_in?
  %li= link_to 'Users', users_path

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/admin.html.haml
!!!
%html{:lang => "en"}
  %head
    %title Блог
    = render 'layouts/admin/header'
  %body
    #wrapper
      = render 'layouts/admin/navbar'
      = render 'layouts/admin/sidebar'
      #page-wrapper
        = render 'layouts/admin/messages'
        = yield
        / /.row
      / /#page-wrapper
    / /#wrapper

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>It</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>

      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
        <% end %>

      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Home</a>

      </div>

        <p class="navbar-text pull-right">

        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>

      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title It
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css", :integrity => "sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7", :rel => "stylesheet"}/
    %script{:crossorigin => "anonymous", :integrity => "sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS", :src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"}
  %body
    %nav.navbar.navbar-default.navbar-static-top{:role => "navigation"}
      .container
        - if notice
          %p.alert.alert-success= notice
        - if alert
          %p.alert.alert-danger= alert
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "/"} Home
        %p.navbar-text.pull-right
          - if user_signed_in?
            Logged in as
            = succeed "." do
              %strong= current_user.email
            = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
            |
            \#{link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'}
          - else
            = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
            |
            \#{link_to "Login", new_user_session_path, :class => 'navbar-link'}
    .container
      = yield

app/views/pages/about.html.haml
- content_for :title do
  About
%h3 About the Website
%p
  This web application was created with
  = link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/')
  from the #{link_to('RailsApps project', 'http://railsapps.github.io/')}.

app/views/posts/_post.html.erb
<li>
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
</li>

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li
          * #{msg}

app/views/shared/_feed.html.haml
- if @feed_items.any?
  %ol.posts= render partial: 'shared/feed_item', collection: @feed_items
  = will_paginate @feed_items

app/views/shared/_feed_item.html.haml
%li{:id => feed_item.id}
  = link_to feed_item.user, feed_item.user
  %span.user
    = link_to feed_item.user.name, feed_item.user
  %span.content= feed_item.content
  %span.timestamp
    Posted #{time_ago_in_words(feed_item.created_at)} ago.

app/views/shared/_post_form.html.haml
= form_for(@post) do |f|
  = render 'shared/error_messages', object: f.object
  = f.file_field :image
  .field
    = f.text_area :content, placeholder: "Create new post..."
  = f.submit "Post", class: "btn btn-large btn-primary"

app/views/users/_user.html.haml
%td= link_to user.name, user
%td= link_to user.email, user

app/views/users/_users.html.haml
%li
  = link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    | #{link_to "delete", user, method: :delete, data: { confirm: "You sure?" }}

app/views/users/index.html.haml
.container
  .row
    %h3 Users
    .column
      %table.table
        %tbody
          - @users.each do |user|
            %tr
              = render user

app/views/users/show.html.haml
%h3 User
%p
  Name: #{@user.name if @user.name}
%p
  Email: #{@user.email if @user.email}
.span8
  - if @user.posts.any?
    %h3
      Posts (#{@user.posts.count})
    %ol.posts= render @posts
    = will_paginate @posts

app/views/visitors/index.html.haml
/ Page Content
.container
  .row
    .col-lg-12.text-center
      %h1 A Bootstrap Starter Template
      %p.lead
        A Bootstrap HTML starter template from
        = succeed "." do
          %a{:href => "http://startbootstrap.com/"} startbootstrap.com
      %ul.list-unstyled
        %li Bootstrap
        %li jQuery
  / /.row
/ /.container